### ISSUE TITLE
Missing documentation and parts

### ISSUE THREAD

**Issue by TechnologyClassroom** [apollobvm/apollobvm#5]
All of the documentation, pictures, and parts from http://oedk.rice.edu/ApolloBVM-DIY should be included on the git or a separate repo.  At this time, there is not a way to collaborate on the rest of the project.

**Comment by th3rring** [comment]
Hi there!

We're not planning on hosting the CAD files right now on Github. We've got a [website](http://oedk.rice.edu/apollobvm) that we've built that includes assembly instructions, videos, and technical documents. Let me know if this isn't effective for your purposes though and we could make some changes to make things more accessible.

**Comment by TechnologyClassroom** [comment]
Requiring registration and keeping the files on dropbox limits access.

Since you already have a github, everything should be available on github and mirrored through whatever other means.  This adds version control and the ability for contributions beyond email.

I can convert the instructions to markdown and submit a pull request to help out with this.

**Comment by th3rring** [comment]
Ya, completely agree. 

The reasoning behind the registration was so that we can keep people in the loop as things progress on our side. We're doing clinical tests today and on Monday so we'd like to be able to easily distribute any findings etc. Also legal here wanted people to have to accept a disclaimer before they've got access to the parts as a precaution.

We're working on trying to have more infrastructure to encourage more collaboration. If you've got any suggestions, they'd definitely be appreciated!

**Comment by TechnologyClassroom** [comment]
With the license, there is nothing stopping anyone from posting the designs on another repo or site as long as there is attribution.  You should post them on your site to keep the project in one place.

Signing up for a mailing list should be encouraged for updates, but should not be a requirement.

**Comment by TechnologyClassroom** [comment]
A quality disclaimer should remove liability.

**Comment by th3rring** [comment]
Thanks for the great suggestions! We'll definitely keep this in mind going forward. I'm going to bring up your feedback with the mechanical team to get their thoughts. 

Going to reopen this issue for the time being as we work this out!

**Comment by TechnologyClassroom** [comment]
Documentation and parts are now part of this repo.  Resolving.
